# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            王小小
tagline:          ''
description:      '菜菜的'
url:              http://wangxiaoxiao88.github.io/

author:
  name:           'xiaoxiao'
  url:            http://wangxiaoxiao88.github.io/

paginate:         5

